<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { fetchBookingById, cancelBooking, getApiErrorMessage } from '@/api'
import type { BookingDto } from '@/types'

const route = useRoute()
const router = useRouter()

const booking = ref<BookingDto | null>(null)
const loading = ref(true)
const error = ref<string | null>(null)

const cancelling = ref(false)
const confirmCancelOpen = ref(false)

onMounted(async () => {
  try {
    booking.value = await fetchBookingById(route.params.id as string)
  } catch (err) {
    const apiMessage = getApiErrorMessage(err)
    error.value = apiMessage ?? 'Booking not found.'
  } finally {
    loading.value = false
  }
})

async function handleCancel() {
  if (!booking.value) return
  cancelling.value = true
  error.value = null
  try {
    await cancelBooking(booking.value.id)
    booking.value = await fetchBookingById(booking.value.id)
  } catch (err) {
    const apiMessage = getApiErrorMessage(err)
    error.value = apiMessage ?? 'Failed to cancel booking. Please try again.'
  } finally {
    cancelling.value = false
  }
}

function requestCancel() {
  if (cancelling.value) return
  confirmCancelOpen.value = true
}

function closeConfirm() {
  if (cancelling.value) return
  confirmCancelOpen.value = false
}

async function confirmCancel() {
  if (cancelling.value) return
  confirmCancelOpen.value = false
  await handleCancel()
}

function formatDateTime(iso: string): string {
  return new Date(iso).toLocaleString('en-GB', {
    dateStyle: 'medium',
    timeStyle: 'short',
  })
}
</script>

<template>
  <div class="detail-view">
    <button class="back-btn" @click="router.push('/')">← Back to booking</button>

    <div v-if="loading" class="loading">Loading booking…</div>
    <div v-else-if="error && !booking" class="alert error">{{ error }}</div>

    <div v-else-if="booking" class="card">
      <div class="card-header">
        <h2>Booking Confirmation</h2>
        <span class="status" :class="{ cancelled: booking.status === 'CANCELLED' }">
          <template v-if="booking.status === 'CANCELLED'">✗ Cancelled</template>
          <template v-else-if="booking.status === 'ACTIVE'">✓ Active</template>
          <template v-else>{{ booking.status }}</template>
        </span>
      </div>

      <div class="section">
        <h3>📋 Booking Details</h3>
        <div class="row">
          <span>Booking ID</span><span>{{ booking.id }}</span>
        </div>
        <div class="row">
          <span>From</span><span>{{ formatDateTime(booking.startTime) }}</span>
        </div>
        <div class="row">
          <span>To</span><span>{{ formatDateTime(booking.endTime) }}</span>
        </div>
        <div class="row">
          <span>Guests</span><span>{{ booking.peopleCount }}</span>
        </div>
      </div>

      <div class="section">
        <h3>👤 Customer Details</h3>
        <div class="row">
          <span>Name</span><span>{{ booking.customerName }}</span>
        </div>
        <div class="row">
          <span>Phone</span><span>{{ booking.customerPhone }}</span>
        </div>
        <div class="row">
          <span>Email</span><span>{{ booking.customerEmail }}</span>
        </div>
      </div>

      <div v-if="error" class="alert error">{{ error }}</div>

      <div v-if="booking.status !== 'CANCELLED'" class="actions">
        <button class="cancel-btn" :disabled="cancelling" @click="requestCancel">
          {{ cancelling ? 'Cancelling…' : 'Cancel Booking' }}
        </button>
      </div>

      <div v-if="booking.status === 'CANCELLED'" class="alert success">
        Your booking has been cancelled successfully.
      </div>
    </div>

    <div v-if="confirmCancelOpen" class="modal-backdrop" @click="closeConfirm">
      <div class="modal" role="dialog" aria-modal="true" @click.stop>
        <h4>Cancel this booking?</h4>
        <p>This action cannot be undone.</p>
        <div class="modal-actions">
          <button class="ghost-btn" :disabled="cancelling" @click="closeConfirm">
            Keep Booking
          </button>
          <button class="danger-btn" :disabled="cancelling" @click="confirmCancel">
            {{ cancelling ? 'Cancelling…' : 'Yes, Cancel' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// Styles were generated by Claude Sonnet 4.6 and verified by the developer
<style scoped>
.detail-view {
  max-width: 600px;
  margin: 40px auto;
  padding: 0 16px;
}

.back-btn {
  background: none;
  border: none;
  color: var(--color-primary-muted);
  font-size: 0.9rem;
  font-weight: 600;
  cursor: pointer;
  padding: 0 0 16px;
  display: block;
}

.back-btn:hover {
  color: var(--color-primary);
}

.loading {
  padding: 60px;
  text-align: center;
  color: var(--color-muted);
}

.card {
  background: var(--color-surface);
  border-radius: var(--radius-xxl);
  padding: 28px 32px;
  box-shadow: var(--shadow-md);
}

.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 24px;
}

h2 {
  margin: 0;
  color: var(--color-primary);
}

.status {
  padding: 4px 12px;
  border-radius: 20px;
  font-size: 0.82rem;
  font-weight: 700;
  background: var(--color-success-bg);
  color: var(--color-success);
  border: 1px solid var(--color-success-border);
}

.status.cancelled {
  background: var(--color-danger-bg);
  color: var(--color-danger);
  border-color: var(--color-danger-border);
}

.section {
  margin-bottom: 20px;
}

h3 {
  margin: 0 0 10px;
  font-size: 0.95rem;
  color: var(--color-muted);
  border-bottom: 1px solid #f0ddd0;
  padding-bottom: 6px;
}

.row {
  display: flex;
  justify-content: space-between;
  padding: 7px 0;
  font-size: 0.9rem;
  border-bottom: 1px solid #faf0ea;
  gap: 12px;
}

.row span:first-child {
  color: var(--color-muted-2);
  font-weight: 600;
  flex-shrink: 0;
}

.actions {
  margin-top: 24px;
}

.cancel-btn {
  width: 100%;
  padding: 12px;
  background: var(--color-danger);
  color: var(--color-surface);
  border: none;
  border-radius: var(--radius-md);
  font-size: 1rem;
  font-weight: 700;
  cursor: pointer;
}

.cancel-btn:hover:not(:disabled) {
  background: #a31515;
}

.cancel-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.modal-backdrop {
  position: fixed;
  inset: 0;
  background: rgba(26, 12, 6, 0.45);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 20px;
  z-index: 20;
}

.modal {
  width: 100%;
  max-width: 420px;
  background: var(--color-surface);
  border-radius: var(--radius-xxl);
  padding: 20px 22px;
  box-shadow: 0 18px 40px rgba(0, 0, 0, 0.22);
}

.modal h4 {
  margin: 0 0 8px;
  color: var(--color-primary);
}

.modal p {
  margin: 0;
  color: var(--color-muted);
  font-size: 0.92rem;
}

.modal-actions {
  display: flex;
  gap: 10px;
  margin-top: 18px;
}

.ghost-btn,
.danger-btn {
  flex: 1;
  padding: 10px 12px;
  border-radius: var(--radius-md);
  font-weight: 700;
  border: 1px solid transparent;
  cursor: pointer;
}

.ghost-btn {
  background: #fff7f0;
  color: var(--color-muted);
  border-color: #f0ddd0;
}

.ghost-btn:hover:not(:disabled) {
  background: #f6e8dc;
}

.danger-btn {
  background: var(--color-danger);
  color: var(--color-surface);
}

.danger-btn:hover:not(:disabled) {
  background: #a31515;
}

.ghost-btn:disabled,
.danger-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.alert {
  padding: 12px 16px;
  border-radius: var(--radius-md);
  margin-top: 16px;
  font-size: 0.9rem;
}

.error {
  background: var(--color-danger-bg);
  color: var(--color-danger);
  border: 1px solid var(--color-danger-border);
}

.success {
  background: var(--color-success-bg);
  color: var(--color-success);
  border: 1px solid var(--color-success-border);
}
</style>
