<script setup lang="ts">
import { computed, ref } from 'vue'
import { type DragState, type TableDto } from '@/types'
import TableCard from './TableCard.vue'
import { calculateFloorSize, GRID_UNIT } from '@/utils/visual'

const props = defineProps<{
  tables: TableDto[]
  recommendedIds: string[]
  selectedId: string | null
  zone: string
  draggable?: boolean
}>()

const emit = defineEmits<{
  (e: 'select', id: string): void
  (e: 'move', payload: { id: string; x: number; y: number }): void
}>()

const drag = ref<DragState | null>(null)
const posOverride = ref<{ x: number; y: number } | null>(null)

const visibleTables = computed(() =>
  props.zone ? props.tables.filter((t) => t.zone === props.zone) : props.tables,
)

const displayedTables = computed(() =>
  visibleTables.value.map((t) => {
    if (drag.value?.tableId === t.id && posOverride.value) {
      return { ...t, x: posOverride.value.x, y: posOverride.value.y }
    }
    return t
  }),
)

const floorSize = computed(() => calculateFloorSize(displayedTables.value))

function onTableMouseDown(e: MouseEvent, table: TableDto) {
  if (!props.draggable) return
  e.preventDefault()
  const el = e.currentTarget as HTMLElement
  const rect = el.getBoundingClientRect()
  drag.value = {
    tableId: table.id,
    offsetX: e.clientX - rect.left,
    offsetY: e.clientY - rect.top,
  }
  posOverride.value = { x: table.x, y: table.y }
}

function onCanvasMouseMove(e: MouseEvent) {
  if (!drag.value) return
  const container = (e.currentTarget as HTMLElement).getBoundingClientRect()
  const newX = Math.max(
    0,
    Math.round((e.clientX - container.left - drag.value.offsetX) / GRID_UNIT),
  )
  const newY = Math.max(0, Math.round((e.clientY - container.top - drag.value.offsetY) / GRID_UNIT))
  posOverride.value = { x: newX, y: newY }
}

function onCanvasMouseUp() {
  if (!drag.value) return
  const tableId = drag.value.tableId
  const pos = posOverride.value
  drag.value = null
  posOverride.value = null
  if (pos) {
    emit('move', { id: tableId, x: pos.x, y: pos.y })
  }
}
</script>

<template>
  <div
    class="floor-plan-wrapper"
    :style="{ width: `${floorSize.width}px`, height: `${floorSize.height}px` }"
  >
    <div
      class="floor-plan"
      :class="{ 'is-draggable': draggable }"
      :style="{ '--grid-unit': `${GRID_UNIT}px` }"
      @mousemove="draggable ? onCanvasMouseMove($event) : undefined"
      @mouseup="draggable ? onCanvasMouseUp() : undefined"
      @mouseleave="draggable ? onCanvasMouseUp() : undefined"
    >
      <TableCard
        v-for="table in displayedTables"
        :key="table.id"
        :table="table"
        :recommended="recommendedIds.includes(table.id)"
        :selected="selectedId === table.id"
        :grid-unit="GRID_UNIT"
        :dragging="draggable && drag?.tableId === table.id"
        :grab-mode="draggable"
        @click="!draggable && emit('select', $event)"
        @mousedown="draggable ? onTableMouseDown($event, table) : undefined"
      />
    </div>
  </div>
</template>

// Styles were generated by Claude Sonnet 4.6 and verified by the developer
<style scoped>
.floor-plan-wrapper {
  display: block;
  border: 2px solid var(--color-border);
  border-radius: var(--radius-xl);
  background: #fdf7f2;
}

.floor-plan {
  position: relative;
  width: 100%;
  height: 100%;

  background-color: #fdf7f2;
  background-image:
    linear-gradient(to right, #e8d5c433 1px, transparent 1px),
    linear-gradient(to bottom, #e8d5c433 1px, transparent 1px);
  background-size: var(--grid-unit, 120px) var(--grid-unit, 120px);
  background-position: 0 0;
}

.floor-plan.is-draggable {
  user-select: none;
}
</style>
